export const FETCH_RATES_SUCCESS = 'FETCH RATES'
export const FETCH_RATES_REQUEST = 'FETCH RATES'
export const FETCH_RATES_FAILURE = 'UNABLE TO FETCH RATES'
export const FILTER_BY_CATEGORY = 'FILTER BANK INFO BY CATEGORY'
export const CONVERT_DOLLAR_TO_CEDI = 'DOLLAR TO CEDI'

